apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: stackrox

resources:
  - ../../secured-cluster.yaml

patches:
  - patch: |-
      - op: replace
        path: /spec/clusterName
        value: secured-cluster01
    target:
      kind: SecuredCluster
      name: stackrox-secured-cluster-services

